# Generated by Django 5.2.16 on 2026-07-10 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Team name (e.g., Germany)", max_length=100),
                ),
                (
                    "fifa_code",
                    models.CharField(
                        help_text="FIFA country code (e.g., GER)",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("A", "Group A"),
                            ("B", "Group B"),
                            ("C", "Group C"),
                            ("D", "Group D"),
                            ("E", "Group E"),
                            ("F", "Group F"),
                            ("G", "Group G"),
                            ("H", "Group H"),
                        ],
                        help_text="Tournament group assignment",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "db_table": "matches_team",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kickoff", models.DateTimeField(help_text="Match start time")),
                (
                    "round",
                    models.CharField(
                        choices=[
                            ("group", "Group Stage"),
                            ("r32", "Round of 32"),
                            ("r16", "Round of 16"),
                            ("qf", "Quarter-Final"),
                            ("sf", "Semi-Final"),
                            ("3rd", "Third Place"),
                            ("final", "Final"),
                        ],
                        help_text="Tournament round",
                        max_length=10,
                    ),
                ),
                (
                    "goals_home",
                    models.IntegerField(
                        blank=True, help_text="Goals scored by home team", null=True
                    ),
                ),
                (
                    "goals_away",
                    models.IntegerField(
                        blank=True, help_text="Goals scored by away team", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("finished", "Finished"),
                        ],
                        default="scheduled",
                        help_text="Match status",
                        max_length=10,
                    ),
                ),
                (
                    "team_away",
                    models.ForeignKey(
                        help_text="Away team",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="away_matches",
                        to="matches.team",
                    ),
                ),
                (
                    "team_home",
                    models.ForeignKey(
                        help_text="Home team",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_matches",
                        to="matches.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "db_table": "matches_match",
                "ordering": ["kickoff"],
            },
        ),
    ]
