# Generated by Django 5.2.16 on 2026-07-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="group",
        ),
        migrations.AddField(
            model_name="team",
            name="is_champion",
            field=models.BooleanField(
                default=False, help_text="Whether this team won the tournament"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="points",
            field=models.IntegerField(default=0, help_text="Championship points"),
        ),
    ]
