# Generated by Django 5.2.16 on 2026-07-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0002_remove_team_group_team_is_champion_team_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="odds_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Category A (odds rank 1-8)"),
                    ("B", "Category B (odds rank 9+)"),
                ],
                help_text="Champion prediction category: A (odds rank 1-8, 20pts) or B (rank 9+, 30pts). Set by admin based on betting odds.",
                max_length=1,
                null=True,
            ),
        ),
    ]
