# Generated by Django 5.2.16 on 2026-08-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0003_add_team_odds_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="external_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="External match ID from football-data.org API",
                null=True,
                unique=True,
            ),
        ),
    ]
