# Generated by Django 5.2.16 on 2026-08-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0004_match_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="winner",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home Team"),
                    ("away", "Away Team"),
                    ("draw", "Draw"),
                ],
                help_text="Match winner from API (home/away/draw). For knockout matches with penalties, this shows the actual winner while goals_home/goals_away contain the score before penalties.",
                max_length=10,
                null=True,
            ),
        ),
    ]
