# Generated by Django 5.2.16 on 2026-08-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0005_match_winner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="is_champion",
        ),
    ]
