# Generated by Django 5.2.16 on 2026-09-24 11:30

from django.db import migrations, models


def backfill_null_strings(apps, schema_editor):
    """Replace NULL with "" so the fields can become non-nullable."""
    Match = apps.get_model("matches", "Match")
    Team = apps.get_model("matches", "Team")

    Match.objects.filter(winner__isnull=True).update(winner="")
    Team.objects.filter(odds_category__isnull=True).update(odds_category="")


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0006_remove_team_is_champion"),
    ]

    operations = [
        migrations.RunPython(backfill_null_strings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="match",
            name="winner",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home Team"),
                    ("away", "Away Team"),
                    ("draw", "Draw"),
                ],
                default="",
                help_text="Match winner from API (home/away/draw). For knockout matches with penalties, this shows the actual winner while goals_home/goals_away contain the score before penalties.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="odds_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Category A (odds rank 1-8)"),
                    ("B", "Category B (odds rank 9+)"),
                ],
                default="",
                help_text="Champion prediction category: A (odds rank 1-8, 20pts) or B (rank 9+, 30pts). Set by admin based on betting odds.",
                max_length=1,
            ),
        ),
    ]
