# Generated by Django 5.2.16 on 2026-10-01 13:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0007_empty_string_defaults_for_winner_and_odds_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Tournament name (e.g., WM 2026)", max_length=100),
                ),
                (
                    "slug",
                    models.SlugField(help_text="Short identifier (e.g., wm-2026)", unique=True),
                ),
                (
                    "api_competition_code",
                    models.CharField(
                        help_text="football-data.org competition code (e.g., WC for World Cup, EC for Euro)",
                        max_length=10,
                    ),
                ),
                (
                    "api_season",
                    models.IntegerField(
                        blank=True,
                        help_text="football-data.org season year, if the API requires one",
                        null=True,
                    ),
                ),
                (
                    "lock_buffer_minutes",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Minutes before kickoff after which predictions are locked",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="The one tournament this installation is currently running",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament",
                "verbose_name_plural": "Tournaments",
                "db_table": "matches_tournament",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="unique_active_tournament",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short round code (e.g., group, r16, final)",
                        max_length=10,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label (e.g., Sechzehntelfinale)",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Position of the round within the tournament, ascending"
                    ),
                ),
                (
                    "multiplier",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Factor applied to the base points of every prediction in this round",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "joker_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of jokers available in this round or its joker pool",
                    ),
                ),
                (
                    "joker_multiplier",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Factor applied to the round score when a joker is active",
                    ),
                ),
                (
                    "joker_pool",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Shared joker pool key; rounds with the same key share one joker limit",
                        max_length=20,
                    ),
                ),
                (
                    "prediction_limit",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Maximum number of matches that may be predicted in this round; empty means all",
                        null=True,
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="Marks the round that decides the champion",
                    ),
                ),
                (
                    "api_stage",
                    models.CharField(
                        help_text="football-data.org stage name (e.g., ROUND_OF_16)",
                        max_length=30,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        help_text="Tournament this round belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="matches.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Round",
                "verbose_name_plural": "Rounds",
                "db_table": "matches_round",
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tournament", "code"),
                        name="unique_round_code_per_tournament",
                    ),
                    models.UniqueConstraint(
                        fields=("tournament", "order"),
                        name="unique_round_order_per_tournament",
                    ),
                    models.UniqueConstraint(
                        fields=("tournament", "api_stage"),
                        name="unique_round_api_stage_per_tournament",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_final", True)),
                        fields=("tournament",),
                        name="unique_final_round_per_tournament",
                    ),
                ],
            },
        ),
    ]
