# Generated by Django 5.2.16 on 2026-07-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_remove_team_group_team_is_champion_team_points"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="predicted_champion",
            field=models.ForeignKey(
                blank=True,
                help_text="The team this user predicts will win the tournament",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="champion_predictions",
                to="matches.team",
            ),
        ),
    ]
