# Generated by Django 5.2.16 on 2026-07-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_predicted_champion"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="exact_match_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of predictions with exact score match (first tiebreaker)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="jokers_used",
            field=models.IntegerField(
                default=0,
                help_text="Number of jokers used on scored predictions (second tiebreaker)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_points",
            field=models.IntegerField(
                default=0,
                help_text="Cached total points from all scored predictions (including champion bonus)",
            ),
        ),
    ]
