# Generated by Django 5.2.16 on 2026-07-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_add_user_statistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ISO 3166-1 alpha-2 country code (e.g., DE, BR, US)",
                max_length=2,
            ),
        ),
    ]
