# Generated by Django 5.2.16 on 2026-07-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_add_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                default="system",
                help_text="User's preferred color theme",
                max_length=10,
            ),
        ),
    ]
