# Generated by Django 5.2.16 on 2026-08-05 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_add_theme_preference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="country_code",
        ),
    ]
