# Generated by Django 5.2.16 on 2026-08-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="champion_bonus_points",
            field=models.IntegerField(
                default=0,
                help_text="Champion prediction bonus points (20 for category A, 30 for category B, 0 if not awarded)",
            ),
        ),
    ]
