# Generated by Django 5.2.16 on 2026-08-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_backfill_champion_bonus_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="champion_bonus_points",
            field=models.IntegerField(
                default=0,
                help_text="Champion prediction bonus points (20 for category A, 30 for category B). Updated live during final.",
            ),
        ),
    ]
