# Generated by Django 5.2.16 on 2026-08-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_champion_bonus_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="global_rank",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Current global leaderboard rank (Olympic-style, updated after each match result)",
                null=True,
            ),
        ),
    ]
