# Generated by Django 5.2.16 on 2026-07-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeaderboardSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this snapshot was created"
                    ),
                ),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("final", "Final"),
                        ],
                        help_text="Type of snapshot (daily, weekly, or final)",
                        max_length=10,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Rankings array: [{rank, user_id, username, total_points, exact_match_count, jokers_used}, ...]"
                    ),
                ),
            ],
            options={
                "verbose_name": "leaderboard snapshot",
                "verbose_name_plural": "leaderboard snapshots",
                "db_table": "scoring_leaderboardsnapshot",
                "ordering": ["-created_at"],
            },
        ),
    ]
