# Generated by Django 5.2.16 on 2026-08-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0002_remove_weekly_snapshots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboardsnapshot",
            name="snapshot_type",
            field=models.CharField(
                choices=[("daily", "Daily"), ("final", "Final")],
                help_text="Type of snapshot (daily or final)",
                max_length=10,
            ),
        ),
    ]
